### ISSUE TITLE
Welcome to best-of-digital-gardens!

### ISSUE THREAD

**Issue by lyz-code** [lyz-code/best-of-digital-gardens#10]
Hi all, I've started a new compilation of digital gardens / second brains / exobrains / TIL / ... using the [best-of](https://github.com/best-of-lists/best-of) template and I wanted to add your sites.

I've gone through the following lists searching for you all:

* [Maggie Appleton's compilation](https://github.com/MaggieAppleton/digital-gardeners)
* [Nikita's compilation](https://wiki.nikitavoloboev.xyz/other/wiki-workflow#similar-wikis-i-liked)
* [Richard Litt's compilation](https://github.com/RichardLitt/meta-knowledge)
* [KasperZutterman's compilation](https://github.com/KasperZutterman/Second-Brain)

I've only added those sites that expose their code in a Github or Gitlab repository, because is how the software extracts the data. As you may see, there are just a few categories, feel free [to add more](https://github.com/lyz-code/best-of-digital-gardens/blob/main/CONTRIBUTING.md#add-a-label).

If you have time, please go through the [`projects.yaml`](https://github.com/lyz-code/best-of-digital-gardens/blob/main/projects.yaml)
to check that the information of your site is correct. Probably I've added the wrong name or there are missing labels, as it was everything done manually and in an afternoon.

Finally if you don't want to be in this compilation, sorry for the inconveniences, please open a PR or [contact me](https://lyz-code.github.io/blue-book/contact/).

@aizatto @plutov @tunix @azappella @Bhupesh-V @b-coimbra @caiogondim @CarlosDelfino @dotcli @d2s @davidgasquez @slowernews @eyalev @theatlasroom @bakke92 @josephrexme @joshwnj @joshpierro @wahyd4 @galileo @narze @MarcLoupias @maxdeviant @MateBoy @mehmetka @tslmy @myles @nicksp @nikitavoloboev @mark1626 @hzlmn @obahareth @psto @prasannavl @aleen42 @younata @RichardLitt @sotayamashita @voxsim @smcaleese @hackergrrl @yoshuawuyts @m0wer @sunflowerno0b @thoughtbot @pawamoy @KyleKing @karlicoss @wayanjimmy @sw-yx

**Comment by pawamoy** [comment]
Hey, thanks for listing my humble blog :blush: I've sent a PR to add a short description.

**Comment by aleen42** [comment]
Thanks for your appreciation, checked it.

**Comment by lyz-code** [comment]
@MaggieAppleton @spences10 @maximevaillancourt @hundredrabbits @gjord @kiwicopple @jethrokuan @secretGeek @leebyron @shreyasminocha @mlubinsky @nkintc @seanbreckenridge @mistermicheels @jessesquires @nbelzer @MikeTannenbaum @davidseah @enkiv2 @rknightuk @eddyerburgh @Nimor111 @jakeisnt @simonw @keyvanakbary @vegarsti @believer @rsarai @irosyadi @flber @XXIIVV

**Comment by m0wer** [comment]
Everything looks fine, thanks!

**Comment by hackergrrl** [comment]
please don't include me

**Comment by spences10** [comment]
Looks fine @lyz-code thanks
