### ISSUE TITLE
Add project: yarden-zamir.com

### ISSUE THREAD

**Issue by Yarden-zamir** [lyz-code/best-of-digital-gardens#21]
**Project details:**

- Project Name: Yarden Zamir - an open sourced 🧠
- Github URL: https://github.com/Yarden-zamir/me
- Category: Productivity
- License:
- Package Managers: 
**Additional context:**

**Comment by lyz-code** [comment]
Hi @Yarden-zamir thanks for taking the time to open the issue, whenever I can I'll update the [projects.yaml](https://github.com/lyz-code/best-of-digital-gardens/blob/main/projects.yaml) if you have some spare time you can do it yourself and send a PR
